config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'


urlpatterns = [
    path('', views.DiaryListView.as_view(),name='list'),
    path('create/', views.DiaryCreateView.as_view(), name='create'),
    path('<uuid:pk>/', views.DiaryDetailView.as_view(),name='detail'),
    path('<uuid:pk>/update/', views.DiaryUpdateView.as_view(),name='update'),
    path('<uuid:pk>/delete/', views.DiaryDeleteView.as_view(),name='delete'),
]

core/models.py
from django.db import models

# Create your models here.

diary/models.py
from django.db import models
from django_boost.models.mixins import UUIDModelMixin,TimeStampModelMixin

# Create your models here.

class Diary(UUIDModelMixin,TimeStampModelMixin):
    title = models.CharField(max_length=128)
    text = models.TextField()

diary/forms.py
from django import forms

from .models import Diary


class DiaryForm(forms.ModelForm):

    class Meta:
        model = Diary
        fields = ('title', 'text')

core/views.py
from django.shortcuts import render

# Create your views here.

diary/views.py
from django.views.generic import *
from django.urls import reverse_lazy

from .models import Diary
from .forms import DiaryForm


class DiaryListView(ListView):
    model = Diary


class DiaryDetailView(DetailView):
    model = Diary


class DiaryUpdateView(UpdateView):
    model = Diary
    form_class = DiaryForm
    success_url = reverse_lazy('diary:list')


class DiaryCreateView(CreateView):
    model = Diary
    form_class = DiaryForm
    success_url = reverse_lazy('diary:list')


class DiaryDeleteView(DeleteView):
    model = Diary
    success_url = reverse_lazy('diary:list')

diary/templates/diary/diary_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>みんなのにっき - 確認</title>

    <link
        href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c:100,300,400,500,700,800,900&display=swap&subset=japanese"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" href="{% static 'css/diary.css' %}">
</head>

<body>
    <header>
        <a href="{% url 'diary:list' %}" id="title-wrapper" class="center">
            <span class="title pink">み</span>
            <span class="title light_blue">ん</span>
            <span class="title teal">な</span>
            <span class="title amber">の</span>
            <span class="title purple">に</span>
            <span class="title light_green">っ</span>
            <span class="title brown">き</span>
        </a>
    </header>
    <div id="contents">
        <div id="diary_wrapper">
            <div id="confirm" class="center">ほんとうに消しちゃうよ？</div>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div id="bt-wrapper" class="center">
                    <a href="{% url 'diary:list' %}" id="diary_form_bt_back" class="bg-light_blue button a_reset">もどる</a>
                    <input type="submit" value="けす" id="diary_form_bt_next" class="bg-red button block">
                </div>
            </form>
        </div>
    </div>
    <footer>
        <div id="copyright" class="center">© 2019 みんなのにっき</div>
    </footer>
</body>

</html>

diary/templates/diary/diary_detail.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>みんなのにっき - 詳細</title>

    <link
        href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c:100,300,400,500,700,800,900&display=swap&subset=japanese"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" href="{% static 'css/diary.css' %}">
</head>

<body>
    <header>
        <a href="{% url 'diary:list' %}" id="title-wrapper" class="center">
            <span class="title pink">み</span>
            <span class="title light_blue">ん</span>
            <span class="title teal">な</span>
            <span class="title amber">の</span>
            <span class="title purple">に</span>
            <span class="title light_green">っ</span>
            <span class="title brown">き</span>
        </a>
    </header>
    <div id="contents">
<div id="diary_wrapper">
    <div id="diary_detail_title" class="">
        {{ object.title }}
    </div>
    <div id="diary_detail_text" class="">
        {{ object.text | linebreaksbr }}
    </div>
    <div id="bt-wrapper" class="center">
        <a href="{% url 'diary:list' %}" id="f_left" class="button bg-light_blue a_reset">もどる</a>
        <a href="{% url 'diary:delete' object.pk %}" id="f_center" class="button bg-red a_reset">けす</a>
        <a href="{% url 'diary:update' object.pk %}" id="f_right" class="button bg-pink a_reset">かえる</a>
    </div>
</div>
    </div>
    <footer>
        <div id="copyright" class="center">© 2019 みんなのにっき</div>
    </footer>
</body>

</html>

diary/templates/diary/diary_form.html
{% load widget_tweaks %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>みんなのにっき - {% if request.path == "/create/" %}作成{% else %}更新{% endif %}</title>

    <link
        href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c:100,300,400,500,700,800,900&display=swap&subset=japanese"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" href="{% static 'css/diary.css' %}">
</head>

<body>
    <header>
        <a href="{% url 'diary:list' %}" id="title-wrapper" class="center">
            <span class="title pink">み</span>
            <span class="title light_blue">ん</span>
            <span class="title teal">な</span>
            <span class="title amber">の</span>
            <span class="title purple">に</span>
            <span class="title light_green">っ</span>
            <span class="title brown">き</span>
        </a>
    </header>
    <div id="contents">
        <div id="diary_wrapper">
            <form action="" method="post">
                {% csrf_token %}

                <div id="diary-title-wrapper">
                    <label for="diary-title">たいとる</label>
                    {{ form.title | attr:"id:diary-title" }}
                </div>

                <br>

                <div id="diary-text-wrapper">
                    <label for="diary-text">ないよう</label>
                    {{ form.text | attr:"id:diary-text" }}
                </div>

                <div id="bt-wrapper" class="center">
                    <a href="{% url 'diary:list' %}" id="diary_form_bt_back"
                        class="bg-light_blue button a_reset">もどる</a>
                    {% if request.path == "/create/" %}
                    <input type="submit" value="つくる" id="diary_form_bt_next" class="bg-pink button block">
                    {% else %}
                    <input type="submit" value="かえる" id="diary_form_bt_next" class="bg-pink button block">
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
    <footer>
        <div id="copyright" class="center">© 2019 みんなのにっき</div>
    </footer>
</body>

</html>

diary/templates/diary/diary_list.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>みんなのにっき - ホーム</title>

    <link
        href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c:100,300,400,500,700,800,900&display=swap&subset=japanese"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" href="{% static 'css/diary.css' %}">
</head>

<body>
    <header>
        <a href="{% url 'diary:list' %}" id="title-wrapper" class="center">
            <span class="title pink">み</span>
            <span class="title light_blue">ん</span>
            <span class="title teal">な</span>
            <span class="title amber">の</span>
            <span class="title purple">に</span>
            <span class="title light_green">っ</span>
            <span class="title brown">き</span>
        </a>
    </header>
    <div id="contents">
<div id="diary_wrapper">
    {% if object_list %}
    <table id="diary_list_table">
        <tr>
            <th>だいめい</th>
            <th>ないよう</th>
        </tr>
        {% for object in object_list %}
        <tr>
            <td>
                <a class="diary_list_a a_reset" href="{% url 'diary:detail' object.pk %}">{{ object.title }}</a>
            </td>
            <td>
                <a class="diary_list_a a_reset" href="{% url 'diary:detail' object.pk %}">ないようだよ</a>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <div id="confirm" class="center">にっきがないよ</div>
    {% endif %}
</div>
    </div>
    <footer>
        <a id="diary_list_bt" class="bg-pink center button a_reset" href="{% url 'diary:create' %}">つくる</a>
        <div id="copyright" class="center">© 2019 みんなのにっき</div>
    </footer>
    <script src="{% static 'js/diary.js' %}"></script>
</body>

</html>